name: Tests On Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

jobs:
  test_basic_alias_workflow_call:
    uses: ./.github/workflows/test_basic_alias_workflow_call.yaml
  test_git_alias_workflow_call:
    uses: ./.github/workflows/test_git_alias_workflow_call.yaml
  test_python_alias_workflow_call:
    uses: ./.github/workflows/test_python_alias_workflow_call.yaml
  test_python_uv_alias_workflow_call:
    uses: ./.github/workflows/test_python_uv_alias_workflow_call.yaml
  test_python_pyenv_alias_workflow_call:
    uses: ./.github/workflows/test_python_pyenv_alias_workflow_call.yaml
  test_update_bashrc:
    uses: ./.github/workflows/test_update_bashrc.yaml
  test_tar_alias_workflow_call:
    uses: ./.github/workflows/test_tar_alias_workflow_call.yaml
