name: test_python_uv_alias

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}
      - name: Setup
        run: |
          git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
          export PYENV_ROOT="$HOME/.pyenv"
          command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
          $PYENV_ROOT/bin/pyenv init
          pyenv -v
      - name: test
        run: |
          . ~/.bashrc
          . ./tests/test_python_pyenv_alias.sh
