name: test_python_uv_alias

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.git-ref }}
      - name: Install requirements
        run: |
          echo "Installing requirements..."
          git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          pyenv -v
      - name: test
        run: |
          . ~/.bashrc
          . ./tests/test_python_pyenv_alias.sh
